DELETE from cities;
INSERT INTO cities VALUES ('01', 'Hà Nội', 'Thành phố Trung ương');
INSERT INTO cities VALUES ('02', 'Hà Giang', 'Tỉnh');
INSERT INTO cities VALUES ('04', 'Cao Bằng', 'Tỉnh');
INSERT INTO cities VALUES ('06', 'Bắc Kạn', 'Tỉnh');
INSERT INTO cities VALUES ('08', 'Tuyên Quang', 'Tỉnh');
INSERT INTO cities VALUES ('10', 'Lào Cai', 'Tỉnh');
INSERT INTO cities VALUES ('11', 'Điện Biên', 'Tỉnh');
INSERT INTO cities VALUES ('12', 'Lai Châu', 'Tỉnh');
INSERT INTO cities VALUES ('14', 'Sơn La', 'Tỉnh');
INSERT INTO cities VALUES ('15', 'Yên Bái', 'Tỉnh');
INSERT INTO cities VALUES ('17', 'Hoà Bình', 'Tỉnh');
INSERT INTO cities VALUES ('19', 'Thái Nguyên', 'Tỉnh');
INSERT INTO cities VALUES ('20', 'Lạng Sơn', 'Tỉnh');
INSERT INTO cities VALUES ('22', 'Quảng Ninh', 'Tỉnh');
INSERT INTO cities VALUES ('24', 'Bắc Giang', 'Tỉnh');
INSERT INTO cities VALUES ('25', 'Phú Thọ', 'Tỉnh');
INSERT INTO cities VALUES ('26', 'Vĩnh Phúc', 'Tỉnh');
INSERT INTO cities VALUES ('27', 'Bắc Ninh', 'Tỉnh');
INSERT INTO cities VALUES ('30', 'Hải Dương', 'Tỉnh');
INSERT INTO cities VALUES ('31', 'Hải Phòng', 'Thành phố Trung ương');
INSERT INTO cities VALUES ('33', 'Hưng Yên', 'Tỉnh');
INSERT INTO cities VALUES ('34', 'Thái Bình', 'Tỉnh');
INSERT INTO cities VALUES ('35', 'Hà Nam', 'Tỉnh');
INSERT INTO cities VALUES ('36', 'Nam Định', 'Tỉnh');
INSERT INTO cities VALUES ('37', 'Ninh Bình', 'Tỉnh');
INSERT INTO cities VALUES ('38', 'Thanh Hóa', 'Tỉnh');
INSERT INTO cities VALUES ('40', 'Nghệ An', 'Tỉnh');
INSERT INTO cities VALUES ('42', 'Hà Tĩnh', 'Tỉnh');
INSERT INTO cities VALUES ('44', 'Quảng Bình', 'Tỉnh');
INSERT INTO cities VALUES ('45', 'Quảng Trị', 'Tỉnh');
INSERT INTO cities VALUES ('46', 'Thừa Thiên Huế', 'Tỉnh');
INSERT INTO cities VALUES ('48', 'Đà Nẵng', 'Thành phố Trung ương');
INSERT INTO cities VALUES ('49', 'Quảng Nam', 'Tỉnh');
INSERT INTO cities VALUES ('51', 'Quảng Ngãi', 'Tỉnh');
INSERT INTO cities VALUES ('52', 'Bình Định', 'Tỉnh');
INSERT INTO cities VALUES ('54', 'Phú Yên', 'Tỉnh');
INSERT INTO cities VALUES ('56', 'Khánh Hòa', 'Tỉnh');
INSERT INTO cities VALUES ('58', 'Ninh Thuận', 'Tỉnh');
INSERT INTO cities VALUES ('60', 'Bình Thuận', 'Tỉnh');
INSERT INTO cities VALUES ('62', 'Kon Tum', 'Tỉnh');
INSERT INTO cities VALUES ('64', 'Gia Lai', 'Tỉnh');
INSERT INTO cities VALUES ('66', 'Đắk Lắk', 'Tỉnh');
INSERT INTO cities VALUES ('67', 'Đắk Nông', 'Tỉnh');
INSERT INTO cities VALUES ('68', 'Lâm Đồng', 'Tỉnh');
INSERT INTO cities VALUES ('70', 'Bình Phước', 'Tỉnh');
INSERT INTO cities VALUES ('72', 'Tây Ninh', 'Tỉnh');
INSERT INTO cities VALUES ('74', 'Bình Dương', 'Tỉnh');
INSERT INTO cities VALUES ('75', 'Đồng Nai', 'Tỉnh');
INSERT INTO cities VALUES ('77', 'Bà Rịa - Vũng Tàu', 'Tỉnh');
INSERT INTO cities VALUES ('79', 'TP Hồ Chí Minh', 'Thành phố Trung ương');
INSERT INTO cities VALUES ('80', 'Long An', 'Tỉnh');
INSERT INTO cities VALUES ('82', 'Tiền Giang', 'Tỉnh');
INSERT INTO cities VALUES ('83', 'Bến Tre', 'Tỉnh');
INSERT INTO cities VALUES ('84', 'Trà Vinh', 'Tỉnh');
INSERT INTO cities VALUES ('86', 'Vĩnh Long', 'Tỉnh');
INSERT INTO cities VALUES ('87', 'Đồng Tháp', 'Tỉnh');
INSERT INTO cities VALUES ('89', 'An Giang', 'Tỉnh');
INSERT INTO cities VALUES ('91', 'Kiên Giang', 'Tỉnh');
INSERT INTO cities VALUES ('92', 'Cần Thơ', 'Thành phố Trung ương');
INSERT INTO cities VALUES ('93', 'Hậu Giang', 'Tỉnh');
INSERT INTO cities VALUES ('94', 'Sóc Trăng', 'Tỉnh');
INSERT INTO cities VALUES ('95', 'Bạc Liêu', 'Tỉnh');
INSERT INTO cities VALUES ('96', 'Cà Mau', 'Tỉnh');
