DELETE from districts;
INSERT INTO districts VALUES ('001', 'Ba Đình', 'Quận', '01');
INSERT INTO districts VALUES ('002', 'Hoàn Kiếm', 'Quận', '01');
INSERT INTO districts VALUES ('003', 'Tây Hồ', 'Quận', '01');
INSERT INTO districts VALUES ('004', 'Long Biên', 'Quận', '01');
INSERT INTO districts VALUES ('005', 'Cầu Giấy', 'Quận', '01');
INSERT INTO districts VALUES ('006', 'Đống Đa', 'Quận', '01');
INSERT INTO districts VALUES ('007', 'Hai Bà Trưng', 'Quận', '01');
INSERT INTO districts VALUES ('008', 'Hoàng Mai', 'Quận', '01');
INSERT INTO districts VALUES ('009', 'Thanh Xuân', 'Quận', '01');
INSERT INTO districts VALUES ('016', 'Sóc Sơn', 'Huyện', '01');
INSERT INTO districts VALUES ('017', 'Đông Anh', 'Huyện', '01');
INSERT INTO districts VALUES ('018', 'Gia Lâm', 'Huyện', '01');
INSERT INTO districts VALUES ('019', 'Nam Từ Liêm', 'Quận', '01');
INSERT INTO districts VALUES ('020', 'Thanh Trì', 'Huyện', '01');
INSERT INTO districts VALUES ('021', 'Bắc Từ Liêm', 'Quận', '01');
INSERT INTO districts VALUES ('024', 'Hà Giang', 'Thành phố', '02');
INSERT INTO districts VALUES ('026', 'Đồng Văn', 'Huyện', '02');
INSERT INTO districts VALUES ('027', 'Mèo Vạc', 'Huyện', '02');
INSERT INTO districts VALUES ('028', 'Yên Minh', 'Huyện', '02');
INSERT INTO districts VALUES ('029', 'Quản Bạ', 'Huyện', '02');
INSERT INTO districts VALUES ('030', 'Vị Xuyên', 'Huyện', '02');
INSERT INTO districts VALUES ('031', 'Bắc Mê', 'Huyện', '02');
INSERT INTO districts VALUES ('032', 'Hoàng Su Phì', 'Huyện', '02');
INSERT INTO districts VALUES ('033', 'Xín Mần', 'Huyện', '02');
INSERT INTO districts VALUES ('034', 'Bắc Quang', 'Huyện', '02');
INSERT INTO districts VALUES ('035', 'Quang Bình', 'Huyện', '02');
INSERT INTO districts VALUES ('040', 'Cao Bằng', 'Thành phố', '04');
INSERT INTO districts VALUES ('042', 'Bảo Lâm', 'Huyện', '04');
INSERT INTO districts VALUES ('043', 'Bảo Lạc', 'Huyện', '04');
INSERT INTO districts VALUES ('044', 'Thông Nông', 'Huyện', '04');
INSERT INTO districts VALUES ('045', 'Hà Quảng', 'Huyện', '04');
INSERT INTO districts VALUES ('046', 'Trà Lĩnh', 'Huyện', '04');
INSERT INTO districts VALUES ('047', 'Trùng Khánh', 'Huyện', '04');
INSERT INTO districts VALUES ('048', 'Hạ Lang', 'Huyện', '04');
INSERT INTO districts VALUES ('049', 'Quảng Uyên', 'Huyện', '04');
INSERT INTO districts VALUES ('050', 'Phục Hoà', 'Huyện', '04');
INSERT INTO districts VALUES ('051', 'Hoà An', 'Huyện', '04');
INSERT INTO districts VALUES ('052', 'Nguyên Bình', 'Huyện', '04');
INSERT INTO districts VALUES ('053', 'Thạch An', 'Huyện', '04');
INSERT INTO districts VALUES ('058', 'Bắc Kạn', 'Thành phố', '06');
INSERT INTO districts VALUES ('060', 'Pác Nặm', 'Huyện', '06');
INSERT INTO districts VALUES ('061', 'Ba Bể', 'Huyện', '06');
INSERT INTO districts VALUES ('062', 'Ngân Sơn', 'Huyện', '06');
INSERT INTO districts VALUES ('063', 'Bạch Thông', 'Huyện', '06');
INSERT INTO districts VALUES ('064', 'Chợ Đồn', 'Huyện', '06');
INSERT INTO districts VALUES ('065', 'Chợ Mới', 'Huyện', '06');
INSERT INTO districts VALUES ('066', 'Na Rì', 'Huyện', '06');
INSERT INTO districts VALUES ('070', 'Tuyên Quang', 'Thành phố', '08');
INSERT INTO districts VALUES ('071', 'Lâm Bình', 'Huyện', '08');
INSERT INTO districts VALUES ('072', 'Nà Hang', 'Huyện', '08');
INSERT INTO districts VALUES ('073', 'Chiêm Hóa', 'Huyện', '08');
INSERT INTO districts VALUES ('074', 'Hàm Yên', 'Huyện', '08');
INSERT INTO districts VALUES ('075', 'Yên Sơn', 'Huyện', '08');
INSERT INTO districts VALUES ('076', 'Sơn Dương', 'Huyện', '08');
INSERT INTO districts VALUES ('080', 'Lào Cai', 'Thành phố', '10');
INSERT INTO districts VALUES ('082', 'Bát Xát', 'Huyện', '10');
INSERT INTO districts VALUES ('083', 'Mường Khương', 'Huyện', '10');
INSERT INTO districts VALUES ('084', 'Si Ma Cai', 'Huyện', '10');
INSERT INTO districts VALUES ('085', 'Bắc Hà', 'Huyện', '10');
INSERT INTO districts VALUES ('086', 'Bảo Thắng', 'Huyện', '10');
INSERT INTO districts VALUES ('087', 'Bảo Yên', 'Huyện', '10');
INSERT INTO districts VALUES ('088', 'Sa Pa', 'Huyện', '10');
INSERT INTO districts VALUES ('089', 'Văn Bàn', 'Huyện', '10');
INSERT INTO districts VALUES ('094', 'Điện Biên Phủ', 'Thành phố', '11');
INSERT INTO districts VALUES ('095', 'Thị Xã Mường Lay', 'Thị xã', '11');
INSERT INTO districts VALUES ('096', 'Mường Nhé', 'Huyện', '11');
INSERT INTO districts VALUES ('097', 'Mường Chà', 'Huyện', '11');
INSERT INTO districts VALUES ('098', 'Tủa Chùa', 'Huyện', '11');
INSERT INTO districts VALUES ('099', 'Tuần Giáo', 'Huyện', '11');
INSERT INTO districts VALUES ('100', 'Điện Biên', 'Huyện', '11');
INSERT INTO districts VALUES ('101', 'Điện Biên Đông', 'Huyện', '11');
INSERT INTO districts VALUES ('102', 'Mường Ảng', 'Huyện', '11');
INSERT INTO districts VALUES ('103', 'Nậm Pồ', 'Huyện', '11');
INSERT INTO districts VALUES ('105', 'Lai Châu', 'Thành phố', '12');
INSERT INTO districts VALUES ('106', 'Tam Đường', 'Huyện', '12');
INSERT INTO districts VALUES ('107', 'Mường Tè', 'Huyện', '12');
INSERT INTO districts VALUES ('108', 'Sìn Hồ', 'Huyện', '12');
INSERT INTO districts VALUES ('109', 'Phong Thổ', 'Huyện', '12');
INSERT INTO districts VALUES ('110', 'Than Uyên', 'Huyện', '12');
INSERT INTO districts VALUES ('111', 'Tân Uyên', 'Huyện', '12');
INSERT INTO districts VALUES ('112', 'Nậm Nhùn', 'Huyện', '12');
INSERT INTO districts VALUES ('116', 'Sơn La', 'Thành phố', '14');
INSERT INTO districts VALUES ('118', 'Quỳnh Nhai', 'Huyện', '14');
INSERT INTO districts VALUES ('119', 'Thuận Châu', 'Huyện', '14');
INSERT INTO districts VALUES ('120', 'Mường La', 'Huyện', '14');
INSERT INTO districts VALUES ('121', 'Bắc Yên', 'Huyện', '14');
INSERT INTO districts VALUES ('122', 'Phù Yên', 'Huyện', '14');
INSERT INTO districts VALUES ('123', 'Mộc Châu', 'Huyện', '14');
INSERT INTO districts VALUES ('124', 'Yên Châu', 'Huyện', '14');
INSERT INTO districts VALUES ('125', 'Mai Sơn', 'Huyện', '14');
INSERT INTO districts VALUES ('126', 'Sông Mã', 'Huyện', '14');
INSERT INTO districts VALUES ('127', 'Sốp Cộp', 'Huyện', '14');
INSERT INTO districts VALUES ('128', 'Vân Hồ', 'Huyện', '14');
INSERT INTO districts VALUES ('132', 'Yên Bái', 'Thành phố', '15');
INSERT INTO districts VALUES ('133', 'Thị xã Nghĩa Lộ', 'Thị xã', '15');
INSERT INTO districts VALUES ('135', 'Lục Yên', 'Huyện', '15');
INSERT INTO districts VALUES ('136', 'Văn Yên', 'Huyện', '15');
INSERT INTO districts VALUES ('137', 'Mù Căng Chải', 'Huyện', '15');
INSERT INTO districts VALUES ('138', 'Trấn Yên', 'Huyện', '15');
INSERT INTO districts VALUES ('139', 'Trạm Tấu', 'Huyện', '15');
INSERT INTO districts VALUES ('140', 'Văn Chấn', 'Huyện', '15');
INSERT INTO districts VALUES ('141', 'Yên Bình', 'Huyện', '15');
INSERT INTO districts VALUES ('148', 'Hòa Bình', 'Thành phố', '17');
INSERT INTO districts VALUES ('150', 'Đà Bắc', 'Huyện', '17');
INSERT INTO districts VALUES ('151', 'Kỳ Sơn', 'Huyện', '17');
INSERT INTO districts VALUES ('152', 'Lương Sơn', 'Huyện', '17');
INSERT INTO districts VALUES ('153', 'Kim Bôi', 'Huyện', '17');
INSERT INTO districts VALUES ('154', 'Cao Phong', 'Huyện', '17');
INSERT INTO districts VALUES ('155', 'Tân Lạc', 'Huyện', '17');
INSERT INTO districts VALUES ('156', 'Mai Châu', 'Huyện', '17');
INSERT INTO districts VALUES ('157', 'Lạc Sơn', 'Huyện', '17');
INSERT INTO districts VALUES ('158', 'Yên Thủy', 'Huyện', '17');
INSERT INTO districts VALUES ('159', 'Lạc Thủy', 'Huyện', '17');
INSERT INTO districts VALUES ('164', 'Thái Nguyên', 'Thành phố', '19');
INSERT INTO districts VALUES ('165', 'Sông Công', 'Thành phố', '19');
INSERT INTO districts VALUES ('167', 'Định Hóa', 'Huyện', '19');
INSERT INTO districts VALUES ('168', 'Phú Lương', 'Huyện', '19');
INSERT INTO districts VALUES ('169', 'Đồng Hỷ', 'Huyện', '19');
INSERT INTO districts VALUES ('170', 'Võ Nhai', 'Huyện', '19');
INSERT INTO districts VALUES ('171', 'Đại Từ', 'Huyện', '19');
INSERT INTO districts VALUES ('172', 'Thị xã Phổ Yên', 'Thị xã', '19');
INSERT INTO districts VALUES ('173', 'Phú Bình', 'Huyện', '19');
INSERT INTO districts VALUES ('178', 'Lạng Sơn', 'Thành phố', '20');
INSERT INTO districts VALUES ('180', 'Tràng Định', 'Huyện', '20');
INSERT INTO districts VALUES ('181', 'Bình Gia', 'Huyện', '20');
INSERT INTO districts VALUES ('182', 'Văn Lãng', 'Huyện', '20');
INSERT INTO districts VALUES ('183', 'Cao Lộc', 'Huyện', '20');
INSERT INTO districts VALUES ('184', 'Văn Quan', 'Huyện', '20');
INSERT INTO districts VALUES ('185', 'Bắc Sơn', 'Huyện', '20');
INSERT INTO districts VALUES ('186', 'Hữu Lũng', 'Huyện', '20');
INSERT INTO districts VALUES ('187', 'Chi Lăng', 'Huyện', '20');
INSERT INTO districts VALUES ('188', 'Lộc Bình', 'Huyện', '20');
INSERT INTO districts VALUES ('189', 'Đình Lập', 'Huyện', '20');
INSERT INTO districts VALUES ('193', 'Hạ Long', 'Thành phố', '22');
INSERT INTO districts VALUES ('194', 'Móng Cái', 'Thành phố', '22');
INSERT INTO districts VALUES ('195', 'Cẩm Phả', 'Thành phố', '22');
INSERT INTO districts VALUES ('196', 'Uông Bí', 'Thành phố', '22');
INSERT INTO districts VALUES ('198', 'Bình Liêu', 'Huyện', '22');
INSERT INTO districts VALUES ('199', 'Tiên Yên', 'Huyện', '22');
INSERT INTO districts VALUES ('200', 'Đầm Hà', 'Huyện', '22');
INSERT INTO districts VALUES ('201', 'Hải Hà', 'Huyện', '22');
INSERT INTO districts VALUES ('202', 'Ba Chẽ', 'Huyện', '22');
INSERT INTO districts VALUES ('203', 'Vân Đồn', 'Huyện', '22');
INSERT INTO districts VALUES ('204', 'Hoành Bồ', 'Huyện', '22');
INSERT INTO districts VALUES ('205', 'Thị xã Đông Triều', 'Thị xã', '22');
INSERT INTO districts VALUES ('206', 'Thị xã Quảng Yên', 'Thị xã', '22');
INSERT INTO districts VALUES ('207', 'Cô Tô', 'Huyện', '22');
INSERT INTO districts VALUES ('213', 'Bắc Giang', 'Thành phố', '24');
INSERT INTO districts VALUES ('215', 'Yên Thế', 'Huyện', '24');
INSERT INTO districts VALUES ('216', 'Tân Yên', 'Huyện', '24');
INSERT INTO districts VALUES ('217', 'Lạng Giang', 'Huyện', '24');
INSERT INTO districts VALUES ('218', 'Lục Nam', 'Huyện', '24');
INSERT INTO districts VALUES ('219', 'Lục Ngạn', 'Huyện', '24');
INSERT INTO districts VALUES ('220', 'Sơn Động', 'Huyện', '24');
INSERT INTO districts VALUES ('221', 'Yên Dũng', 'Huyện', '24');
INSERT INTO districts VALUES ('222', 'Việt Yên', 'Huyện', '24');
INSERT INTO districts VALUES ('223', 'Hiệp Hòa', 'Huyện', '24');
INSERT INTO districts VALUES ('227', 'Việt Trì', 'Thành phố', '25');
INSERT INTO districts VALUES ('228', 'Thị xã Phú Thọ', 'Thị xã', '25');
INSERT INTO districts VALUES ('230', 'Đoan Hùng', 'Huyện', '25');
INSERT INTO districts VALUES ('231', 'Hạ Hoà', 'Huyện', '25');
INSERT INTO districts VALUES ('232', 'Thanh Ba', 'Huyện', '25');
INSERT INTO districts VALUES ('233', 'Phù Ninh', 'Huyện', '25');
INSERT INTO districts VALUES ('234', 'Yên Lập', 'Huyện', '25');
INSERT INTO districts VALUES ('235', 'Cẩm Khê', 'Huyện', '25');
INSERT INTO districts VALUES ('236', 'Tam Nông', 'Huyện', '25');
INSERT INTO districts VALUES ('237', 'Lâm Thao', 'Huyện', '25');
INSERT INTO districts VALUES ('238', 'Thanh Sơn', 'Huyện', '25');
INSERT INTO districts VALUES ('239', 'Thanh Thuỷ', 'Huyện', '25');
INSERT INTO districts VALUES ('240', 'Tân Sơn', 'Huyện', '25');
INSERT INTO districts VALUES ('243', 'Vĩnh Yên', 'Thành phố', '26');
INSERT INTO districts VALUES ('244', 'Thị xã Phúc Yên', 'Thị xã', '26');
INSERT INTO districts VALUES ('246', 'Lập Thạch', 'Huyện', '26');
INSERT INTO districts VALUES ('247', 'Tam Dương', 'Huyện', '26');
INSERT INTO districts VALUES ('248', 'Tam Đảo', 'Huyện', '26');
INSERT INTO districts VALUES ('249', 'Bình Xuyên', 'Huyện', '26');
INSERT INTO districts VALUES ('250', 'Mê Linh', 'Huyện', '01');
INSERT INTO districts VALUES ('251', 'Yên Lạc', 'Huyện', '26');
INSERT INTO districts VALUES ('252', 'Vĩnh Tường', 'Huyện', '26');
INSERT INTO districts VALUES ('253', 'Sông Lô', 'Huyện', '26');
INSERT INTO districts VALUES ('256', 'Bắc Ninh', 'Thành phố', '27');
INSERT INTO districts VALUES ('258', 'Yên Phong', 'Huyện', '27');
INSERT INTO districts VALUES ('259', 'Quế Võ', 'Huyện', '27');
INSERT INTO districts VALUES ('260', 'Tiên Du', 'Huyện', '27');
INSERT INTO districts VALUES ('261', 'Thị xã Từ Sơn', 'Thị xã', '27');
INSERT INTO districts VALUES ('262', 'Thuận Thành', 'Huyện', '27');
INSERT INTO districts VALUES ('263', 'Gia Bình', 'Huyện', '27');
INSERT INTO districts VALUES ('264', 'Lương Tài', 'Huyện', '27');
INSERT INTO districts VALUES ('268', 'Hà Đông', 'Quận', '01');
INSERT INTO districts VALUES ('269', 'Thị xã Sơn Tây', 'Thị xã', '01');
INSERT INTO districts VALUES ('271', 'Ba Vì', 'Huyện', '01');
INSERT INTO districts VALUES ('272', 'Phúc Thọ', 'Huyện', '01');
INSERT INTO districts VALUES ('273', 'Đan Phượng', 'Huyện', '01');
INSERT INTO districts VALUES ('274', 'Hoài Đức', 'Huyện', '01');
INSERT INTO districts VALUES ('275', 'Quốc Oai', 'Huyện', '01');
INSERT INTO districts VALUES ('276', 'Thạch Thất', 'Huyện', '01');
INSERT INTO districts VALUES ('277', 'Chương Mỹ', 'Huyện', '01');
INSERT INTO districts VALUES ('278', 'Thanh Oai', 'Huyện', '01');
INSERT INTO districts VALUES ('279', 'Thường Tín', 'Huyện', '01');
INSERT INTO districts VALUES ('280', 'Phú Xuyên', 'Huyện', '01');
INSERT INTO districts VALUES ('281', 'Ứng Hòa', 'Huyện', '01');
INSERT INTO districts VALUES ('282', 'Mỹ Đức', 'Huyện', '01');
INSERT INTO districts VALUES ('288', 'Hải Dương', 'Thành phố', '30');
INSERT INTO districts VALUES ('290', 'Thị xã Chí Linh', 'Thị xã', '30');
INSERT INTO districts VALUES ('291', 'Nam Sách', 'Huyện', '30');
INSERT INTO districts VALUES ('292', 'Kinh Môn', 'Huyện', '30');
INSERT INTO districts VALUES ('293', 'Kim Thành', 'Huyện', '30');
INSERT INTO districts VALUES ('294', 'Thanh Hà', 'Huyện', '30');
INSERT INTO districts VALUES ('295', 'Cẩm Giàng', 'Huyện', '30');
INSERT INTO districts VALUES ('296', 'Bình Giang', 'Huyện', '30');
INSERT INTO districts VALUES ('297', 'Gia Lộc', 'Huyện', '30');
INSERT INTO districts VALUES ('298', 'Tứ Kỳ', 'Huyện', '30');
INSERT INTO districts VALUES ('299', 'Ninh Giang', 'Huyện', '30');
INSERT INTO districts VALUES ('300', 'Thanh Miện', 'Huyện', '30');
INSERT INTO districts VALUES ('303', 'Hồng Bàng', 'Quận', '31');
INSERT INTO districts VALUES ('304', 'Ngô Quyền', 'Quận', '31');
INSERT INTO districts VALUES ('305', 'Lê Chân', 'Quận', '31');
INSERT INTO districts VALUES ('306', 'Hải An', 'Quận', '31');
INSERT INTO districts VALUES ('307', 'Kiến An', 'Quận', '31');
INSERT INTO districts VALUES ('308', 'Đồ Sơn', 'Quận', '31');
INSERT INTO districts VALUES ('309', 'Dương Kinh', 'Quận', '31');
INSERT INTO districts VALUES ('311', 'Thuỷ Nguyên', 'Huyện', '31');
INSERT INTO districts VALUES ('312', 'An Dương', 'Huyện', '31');
INSERT INTO districts VALUES ('313', 'An Lão', 'Huyện', '31');
INSERT INTO districts VALUES ('314', 'Kiến Thuỵ', 'Huyện', '31');
INSERT INTO districts VALUES ('315', 'Tiên Lãng', 'Huyện', '31');
INSERT INTO districts VALUES ('316', 'Vĩnh Bảo', 'Huyện', '31');
INSERT INTO districts VALUES ('317', 'Cát Hải', 'Huyện', '31');
INSERT INTO districts VALUES ('318', 'Bạch Long Vĩ', 'Huyện', '31');
INSERT INTO districts VALUES ('323', 'Hưng Yên', 'Thành phố', '33');
INSERT INTO districts VALUES ('325', 'Văn Lâm', 'Huyện', '33');
INSERT INTO districts VALUES ('326', 'Văn Giang', 'Huyện', '33');
INSERT INTO districts VALUES ('327', 'Yên Mỹ', 'Huyện', '33');
INSERT INTO districts VALUES ('328', 'Mỹ Hào', 'Huyện', '33');
INSERT INTO districts VALUES ('329', 'Ân Thi', 'Huyện', '33');
INSERT INTO districts VALUES ('330', 'Khoái Châu', 'Huyện', '33');
INSERT INTO districts VALUES ('331', 'Kim Động', 'Huyện', '33');
INSERT INTO districts VALUES ('332', 'Tiên Lữ', 'Huyện', '33');
INSERT INTO districts VALUES ('333', 'Phù Cừ', 'Huyện', '33');
INSERT INTO districts VALUES ('336', 'Thái Bình', 'Thành phố', '34');
INSERT INTO districts VALUES ('338', 'Quỳnh Phụ', 'Huyện', '34');
INSERT INTO districts VALUES ('339', 'Hưng Hà', 'Huyện', '34');
INSERT INTO districts VALUES ('340', 'Đông Hưng', 'Huyện', '34');
INSERT INTO districts VALUES ('341', 'Thái Thụy', 'Huyện', '34');
INSERT INTO districts VALUES ('342', 'Tiền Hải', 'Huyện', '34');
INSERT INTO districts VALUES ('343', 'Kiến Xương', 'Huyện', '34');
INSERT INTO districts VALUES ('344', 'Vũ Thư', 'Huyện', '34');
INSERT INTO districts VALUES ('347', 'Phủ Lý', 'Thành phố', '35');
INSERT INTO districts VALUES ('349', 'Duy Tiên', 'Huyện', '35');
INSERT INTO districts VALUES ('350', 'Kim Bảng', 'Huyện', '35');
INSERT INTO districts VALUES ('351', 'Thanh Liêm', 'Huyện', '35');
INSERT INTO districts VALUES ('352', 'Bình Lục', 'Huyện', '35');
INSERT INTO districts VALUES ('353', 'Lý Nhân', 'Huyện', '35');
INSERT INTO districts VALUES ('356', 'Nam Định', 'Thành phố', '36');
INSERT INTO districts VALUES ('358', 'Mỹ Lộc', 'Huyện', '36');
INSERT INTO districts VALUES ('359', 'Vụ Bản', 'Huyện', '36');
INSERT INTO districts VALUES ('360', 'Ý Yên', 'Huyện', '36');
INSERT INTO districts VALUES ('361', 'Nghĩa Hưng', 'Huyện', '36');
INSERT INTO districts VALUES ('362', 'Nam Trực', 'Huyện', '36');
INSERT INTO districts VALUES ('363', 'Trực Ninh', 'Huyện', '36');
INSERT INTO districts VALUES ('364', 'Xuân Trường', 'Huyện', '36');
INSERT INTO districts VALUES ('365', 'Giao Thủy', 'Huyện', '36');
INSERT INTO districts VALUES ('366', 'Hải Hậu', 'Huyện', '36');
INSERT INTO districts VALUES ('369', 'Ninh Bình', 'Thành phố', '37');
INSERT INTO districts VALUES ('370', 'Tam Điệp', 'Thành phố', '37');
INSERT INTO districts VALUES ('372', 'Nho Quan', 'Huyện', '37');
INSERT INTO districts VALUES ('373', 'Gia Viễn', 'Huyện', '37');
INSERT INTO districts VALUES ('374', 'Hoa Lư', 'Huyện', '37');
INSERT INTO districts VALUES ('375', 'Yên Khánh', 'Huyện', '37');
INSERT INTO districts VALUES ('376', 'Kim Sơn', 'Huyện', '37');
INSERT INTO districts VALUES ('377', 'Yên Mô', 'Huyện', '37');
INSERT INTO districts VALUES ('380', 'Thanh Hóa', 'Thành phố', '38');
INSERT INTO districts VALUES ('381', 'Thị xã Bỉm Sơn', 'Thị xã', '38');
INSERT INTO districts VALUES ('382', 'Thị xã Sầm Sơn', 'Thị xã', '38');
INSERT INTO districts VALUES ('384', 'Mường Lát', 'Huyện', '38');
INSERT INTO districts VALUES ('385', 'Quan Hóa', 'Huyện', '38');
INSERT INTO districts VALUES ('386', 'Bá Thước', 'Huyện', '38');
INSERT INTO districts VALUES ('387', 'Quan Sơn', 'Huyện', '38');
INSERT INTO districts VALUES ('388', 'Lang Chánh', 'Huyện', '38');
INSERT INTO districts VALUES ('389', 'Ngọc Lặc', 'Huyện', '38');
INSERT INTO districts VALUES ('390', 'Cẩm Thủy', 'Huyện', '38');
INSERT INTO districts VALUES ('391', 'Thạch Thành', 'Huyện', '38');
INSERT INTO districts VALUES ('392', 'Hà Trung', 'Huyện', '38');
INSERT INTO districts VALUES ('393', 'Vĩnh Lộc', 'Huyện', '38');
INSERT INTO districts VALUES ('394', 'Yên Định', 'Huyện', '38');
INSERT INTO districts VALUES ('395', 'Thọ Xuân', 'Huyện', '38');
INSERT INTO districts VALUES ('396', 'Thường Xuân', 'Huyện', '38');
INSERT INTO districts VALUES ('397', 'Triệu Sơn', 'Huyện', '38');
INSERT INTO districts VALUES ('398', 'Thiệu Hóa', 'Huyện', '38');
INSERT INTO districts VALUES ('399', 'Hoằng Hóa', 'Huyện', '38');
INSERT INTO districts VALUES ('400', 'Hậu Lộc', 'Huyện', '38');
INSERT INTO districts VALUES ('401', 'Nga Sơn', 'Huyện', '38');
INSERT INTO districts VALUES ('402', 'Như Xuân', 'Huyện', '38');
INSERT INTO districts VALUES ('403', 'Như Thanh', 'Huyện', '38');
INSERT INTO districts VALUES ('404', 'Nông Cống', 'Huyện', '38');
INSERT INTO districts VALUES ('405', 'Đông Sơn', 'Huyện', '38');
INSERT INTO districts VALUES ('406', 'Quảng Xương', 'Huyện', '38');
INSERT INTO districts VALUES ('407', 'Tĩnh Gia', 'Huyện', '38');
INSERT INTO districts VALUES ('412', 'Vinh', 'Thành phố', '40');
INSERT INTO districts VALUES ('413', 'Thị xã Cửa Lò', 'Thị xã', '40');
INSERT INTO districts VALUES ('414', 'Thị xã Thái Hoà', 'Thị xã', '40');
INSERT INTO districts VALUES ('415', 'Quế Phong', 'Huyện', '40');
INSERT INTO districts VALUES ('416', 'Quỳ Châu', 'Huyện', '40');
INSERT INTO districts VALUES ('417', 'Kỳ Sơn', 'Huyện', '40');
INSERT INTO districts VALUES ('418', 'Tương Dương', 'Huyện', '40');
INSERT INTO districts VALUES ('419', 'Nghĩa Đàn', 'Huyện', '40');
INSERT INTO districts VALUES ('420', 'Quỳ Hợp', 'Huyện', '40');
INSERT INTO districts VALUES ('421', 'Quỳnh Lưu', 'Huyện', '40');
INSERT INTO districts VALUES ('422', 'Con Cuông', 'Huyện', '40');
INSERT INTO districts VALUES ('423', 'Tân Kỳ', 'Huyện', '40');
INSERT INTO districts VALUES ('424', 'Anh Sơn', 'Huyện', '40');
INSERT INTO districts VALUES ('425', 'Diễn Châu', 'Huyện', '40');
INSERT INTO districts VALUES ('426', 'Yên Thành', 'Huyện', '40');
INSERT INTO districts VALUES ('427', 'Đô Lương', 'Huyện', '40');
INSERT INTO districts VALUES ('428', 'Thanh Chương', 'Huyện', '40');
INSERT INTO districts VALUES ('429', 'Nghi Lộc', 'Huyện', '40');
INSERT INTO districts VALUES ('430', 'Nam Đàn', 'Huyện', '40');
INSERT INTO districts VALUES ('431', 'Hưng Nguyên', 'Huyện', '40');
INSERT INTO districts VALUES ('432', 'Thị xã Hoàng Mai', 'Thị xã', '40');
INSERT INTO districts VALUES ('436', 'Hà Tĩnh', 'Thành phố', '42');
INSERT INTO districts VALUES ('437', 'Thị xã Hồng Lĩnh', 'Thị xã', '42');
INSERT INTO districts VALUES ('439', 'Hương Sơn', 'Huyện', '42');
INSERT INTO districts VALUES ('440', 'Đức Thọ', 'Huyện', '42');
INSERT INTO districts VALUES ('441', 'Vũ Quang', 'Huyện', '42');
INSERT INTO districts VALUES ('442', 'Nghi Xuân', 'Huyện', '42');
INSERT INTO districts VALUES ('443', 'Can Lộc', 'Huyện', '42');
INSERT INTO districts VALUES ('444', 'Hương Khê', 'Huyện', '42');
INSERT INTO districts VALUES ('445', 'Thạch Hà', 'Huyện', '42');
INSERT INTO districts VALUES ('446', 'Cẩm Xuyên', 'Huyện', '42');
INSERT INTO districts VALUES ('447', 'Kỳ Anh', 'Huyện', '42');
INSERT INTO districts VALUES ('448', 'Lộc Hà', 'Huyện', '42');
INSERT INTO districts VALUES ('449', 'Thị xã Kỳ Anh', 'Thị xã', '42');
INSERT INTO districts VALUES ('450', 'Đồng Hới', 'Thành phố', '44');
INSERT INTO districts VALUES ('452', 'Minh Hóa', 'Huyện', '44');
INSERT INTO districts VALUES ('453', 'Tuyên Hóa', 'Huyện', '44');
INSERT INTO districts VALUES ('454', 'Quảng Trạch', 'Thị xã', '44');
INSERT INTO districts VALUES ('455', 'Bố Trạch', 'Huyện', '44');
INSERT INTO districts VALUES ('456', 'Quảng Ninh', 'Huyện', '44');
INSERT INTO districts VALUES ('457', 'Lệ Thủy', 'Huyện', '44');
INSERT INTO districts VALUES ('458', 'Thị xã Ba Đồn', 'Huyện', '44');
INSERT INTO districts VALUES ('461', 'Đông Hà', 'Thành phố', '45');
INSERT INTO districts VALUES ('462', 'Thị xã Quảng Trị', 'Thị xã', '45');
INSERT INTO districts VALUES ('464', 'Vĩnh Linh', 'Huyện', '45');
INSERT INTO districts VALUES ('465', 'Hướng Hóa', 'Huyện', '45');
INSERT INTO districts VALUES ('466', 'Gio Linh', 'Huyện', '45');
INSERT INTO districts VALUES ('467', 'Đa Krông', 'Huyện', '45');
INSERT INTO districts VALUES ('468', 'Cam Lộ', 'Huyện', '45');
INSERT INTO districts VALUES ('469', 'Triệu Phong', 'Huyện', '45');
INSERT INTO districts VALUES ('470', 'Hải Lăng', 'Huyện', '45');
INSERT INTO districts VALUES ('471', 'Cồn Cỏ', 'Huyện', '45');
INSERT INTO districts VALUES ('474', 'Huế', 'Thành phố', '46');
INSERT INTO districts VALUES ('476', 'Phong Điền', 'Huyện', '46');
INSERT INTO districts VALUES ('477', 'Quảng Điền', 'Huyện', '46');
INSERT INTO districts VALUES ('478', 'Phú Vang', 'Huyện', '46');
INSERT INTO districts VALUES ('479', 'Thị xã Hương Thủy', 'Thị xã', '46');
INSERT INTO districts VALUES ('480', 'Thị xã Hương Trà', 'Thị xã', '46');
INSERT INTO districts VALUES ('481', 'A Lưới', 'Huyện', '46');
INSERT INTO districts VALUES ('482', 'Phú Lộc', 'Huyện', '46');
INSERT INTO districts VALUES ('483', 'Nam Đông', 'Huyện', '46');
INSERT INTO districts VALUES ('490', 'Liên Chiểu', 'Quận', '48');
INSERT INTO districts VALUES ('491', 'Thanh Khê', 'Quận', '48');
INSERT INTO districts VALUES ('492', 'Hải Châu', 'Quận', '48');
INSERT INTO districts VALUES ('493', 'Sơn Trà', 'Quận', '48');
INSERT INTO districts VALUES ('494', 'Ngũ Hành Sơn', 'Quận', '48');
INSERT INTO districts VALUES ('495', 'Cẩm Lệ', 'Quận', '48');
INSERT INTO districts VALUES ('497', 'Hòa Vang', 'Huyện', '48');
INSERT INTO districts VALUES ('498', 'Hoàng Sa', 'Huyện', '48');
INSERT INTO districts VALUES ('502', 'Tam Kỳ', 'Thành phố', '49');
INSERT INTO districts VALUES ('503', 'Hội An', 'Thành phố', '49');
INSERT INTO districts VALUES ('504', 'Tây Giang', 'Huyện', '49');
INSERT INTO districts VALUES ('505', 'Đông Giang', 'Huyện', '49');
INSERT INTO districts VALUES ('506', 'Đại Lộc', 'Huyện', '49');
INSERT INTO districts VALUES ('507', 'Thị xã Điện Bàn', 'Thị xã', '49');
INSERT INTO districts VALUES ('508', 'Duy Xuyên', 'Huyện', '49');
INSERT INTO districts VALUES ('509', 'Quế Sơn', 'Huyện', '49');
INSERT INTO districts VALUES ('510', 'Nam Giang', 'Huyện', '49');
INSERT INTO districts VALUES ('511', 'Phước Sơn', 'Huyện', '49');
INSERT INTO districts VALUES ('512', 'Hiệp Đức', 'Huyện', '49');
INSERT INTO districts VALUES ('513', 'Thăng Bình', 'Huyện', '49');
INSERT INTO districts VALUES ('514', 'Tiên Phước', 'Huyện', '49');
INSERT INTO districts VALUES ('515', 'Bắc Trà My', 'Huyện', '49');
INSERT INTO districts VALUES ('516', 'Nam Trà My', 'Huyện', '49');
INSERT INTO districts VALUES ('517', 'Núi Thành', 'Huyện', '49');
INSERT INTO districts VALUES ('518', 'Phú Ninh', 'Huyện', '49');
INSERT INTO districts VALUES ('519', 'Nông Sơn', 'Huyện', '49');
INSERT INTO districts VALUES ('522', 'Quảng Ngãi', 'Thành phố', '51');
INSERT INTO districts VALUES ('524', 'Bình Sơn', 'Huyện', '51');
INSERT INTO districts VALUES ('525', 'Trà Bồng', 'Huyện', '51');
INSERT INTO districts VALUES ('526', 'Tây Trà', 'Huyện', '51');
INSERT INTO districts VALUES ('527', 'Sơn Tịnh', 'Huyện', '51');
INSERT INTO districts VALUES ('528', 'Tư Nghĩa', 'Huyện', '51');
INSERT INTO districts VALUES ('529', 'Sơn Hà', 'Huyện', '51');
INSERT INTO districts VALUES ('530', 'Sơn Tây', 'Huyện', '51');
INSERT INTO districts VALUES ('531', 'Minh Long', 'Huyện', '51');
INSERT INTO districts VALUES ('532', 'Nghĩa Hành', 'Huyện', '51');
INSERT INTO districts VALUES ('533', 'Mộ Đức', 'Huyện', '51');
INSERT INTO districts VALUES ('534', 'Đức Phổ', 'Huyện', '51');
INSERT INTO districts VALUES ('535', 'Ba Tơ', 'Huyện', '51');
INSERT INTO districts VALUES ('536', 'Lý Sơn', 'Huyện', '51');
INSERT INTO districts VALUES ('540', 'Qui Nhơn', 'Thành phố', '52');
INSERT INTO districts VALUES ('542', 'An Lão', 'Huyện', '52');
INSERT INTO districts VALUES ('543', 'Hoài Nhơn', 'Huyện', '52');
INSERT INTO districts VALUES ('544', 'Hoài Ân', 'Huyện', '52');
INSERT INTO districts VALUES ('545', 'Phù Mỹ', 'Huyện', '52');
INSERT INTO districts VALUES ('546', 'Vĩnh Thạnh', 'Huyện', '52');
INSERT INTO districts VALUES ('547', 'Tây Sơn', 'Huyện', '52');
INSERT INTO districts VALUES ('548', 'Phù Cát', 'Huyện', '52');
INSERT INTO districts VALUES ('549', 'Thị xã An Nhơn', 'Thị xã', '52');
INSERT INTO districts VALUES ('550', 'Tuy Phước', 'Huyện', '52');
INSERT INTO districts VALUES ('551', 'Vân Canh', 'Huyện', '52');
INSERT INTO districts VALUES ('555', 'Tuy Hoà', 'Thành phố', '54');
INSERT INTO districts VALUES ('557', 'Thị xã Sông Cầu', 'Thị xã', '54');
INSERT INTO districts VALUES ('558', 'Đồng Xuân', 'Huyện', '54');
INSERT INTO districts VALUES ('559', 'Tuy An', 'Huyện', '54');
INSERT INTO districts VALUES ('560', 'Sơn Hòa', 'Huyện', '54');
INSERT INTO districts VALUES ('561', 'Sông Hinh', 'Huyện', '54');
INSERT INTO districts VALUES ('562', 'Tây Hoà', 'Huyện', '54');
INSERT INTO districts VALUES ('563', 'Phú Hoà', 'Huyện', '54');
INSERT INTO districts VALUES ('564', 'Đông Hòa', 'Huyện', '54');
INSERT INTO districts VALUES ('568', 'Nha Trang', 'Thành phố', '56');
INSERT INTO districts VALUES ('569', 'Cam Ranh', 'Thành phố', '56');
INSERT INTO districts VALUES ('570', 'Cam Lâm', 'Huyện', '56');
INSERT INTO districts VALUES ('571', 'Vạn Ninh', 'Huyện', '56');
INSERT INTO districts VALUES ('572', 'Thị xã Ninh Hòa', 'Thị xã', '56');
INSERT INTO districts VALUES ('573', 'Khánh Vĩnh', 'Huyện', '56');
INSERT INTO districts VALUES ('574', 'Diên Khánh', 'Huyện', '56');
INSERT INTO districts VALUES ('575', 'Khánh Sơn', 'Huyện', '56');
INSERT INTO districts VALUES ('576', 'Trường Sa', 'Huyện', '56');
INSERT INTO districts VALUES ('582', 'Phan Rang-Tháp Chàm', 'Thành phố', '58');
INSERT INTO districts VALUES ('584', 'Bác Ái', 'Huyện', '58');
INSERT INTO districts VALUES ('585', 'Ninh Sơn', 'Huyện', '58');
INSERT INTO districts VALUES ('586', 'Ninh Hải', 'Huyện', '58');
INSERT INTO districts VALUES ('587', 'Ninh Phước', 'Huyện', '58');
INSERT INTO districts VALUES ('588', 'Thuận Bắc', 'Huyện', '58');
INSERT INTO districts VALUES ('589', 'Thuận Nam', 'Huyện', '58');
INSERT INTO districts VALUES ('593', 'Phan Thiết', 'Thành phố', '60');
INSERT INTO districts VALUES ('594', 'Thị xã La Gi', 'Thị xã', '60');
INSERT INTO districts VALUES ('595', 'Tuy Phong', 'Huyện', '60');
INSERT INTO districts VALUES ('596', 'Bắc Bình', 'Huyện', '60');
INSERT INTO districts VALUES ('597', 'Hàm Thuận Bắc', 'Huyện', '60');
INSERT INTO districts VALUES ('598', 'Hàm Thuận Nam', 'Huyện', '60');
INSERT INTO districts VALUES ('599', 'Tánh Linh', 'Huyện', '60');
INSERT INTO districts VALUES ('600', 'Đức Linh', 'Huyện', '60');
INSERT INTO districts VALUES ('601', 'Hàm Tân', 'Huyện', '60');
INSERT INTO districts VALUES ('602', 'Phú Quí', 'Huyện', '60');
INSERT INTO districts VALUES ('608', 'Kon Tum', 'Thành phố', '62');
INSERT INTO districts VALUES ('610', 'Đắk Glei', 'Huyện', '62');
INSERT INTO districts VALUES ('611', 'Ngọc Hồi', 'Huyện', '62');
INSERT INTO districts VALUES ('612', 'Đắk Tô', 'Huyện', '62');
INSERT INTO districts VALUES ('613', 'Kon Plông', 'Huyện', '62');
INSERT INTO districts VALUES ('614', 'Kon Rẫy', 'Huyện', '62');
INSERT INTO districts VALUES ('615', 'Đắk Hà', 'Huyện', '62');
INSERT INTO districts VALUES ('616', 'Sa Thầy', 'Huyện', '62');
INSERT INTO districts VALUES ('617', 'Tu Mơ Rông', 'Huyện', '62');
INSERT INTO districts VALUES ('618', 'Ia H Drai', 'Huyện', '62');
INSERT INTO districts VALUES ('622', 'Pleiku', 'Thành phố', '64');
INSERT INTO districts VALUES ('623', 'Thị xã An Khê', 'Thị xã', '64');
INSERT INTO districts VALUES ('624', 'Thị xã Ayun Pa', 'Thị xã', '64');
INSERT INTO districts VALUES ('625', 'KBang', 'Huyện', '64');
INSERT INTO districts VALUES ('626', 'Đăk Đoa', 'Huyện', '64');
INSERT INTO districts VALUES ('627', 'Chư Păh', 'Huyện', '64');
INSERT INTO districts VALUES ('628', 'Ia Grai', 'Huyện', '64');
INSERT INTO districts VALUES ('629', 'Mang Yang', 'Huyện', '64');
INSERT INTO districts VALUES ('630', 'Kông Chro', 'Huyện', '64');
INSERT INTO districts VALUES ('631', 'Đức Cơ', 'Huyện', '64');
INSERT INTO districts VALUES ('632', 'Chư Prông', 'Huyện', '64');
INSERT INTO districts VALUES ('633', 'Chư Sê', 'Huyện', '64');
INSERT INTO districts VALUES ('634', 'Đăk Pơ', 'Huyện', '64');
INSERT INTO districts VALUES ('635', 'Ia Pa', 'Huyện', '64');
INSERT INTO districts VALUES ('637', 'Krông Pa', 'Huyện', '64');
INSERT INTO districts VALUES ('638', 'Phú Thiện', 'Huyện', '64');
INSERT INTO districts VALUES ('639', 'Chư Pưh', 'Huyện', '64');
INSERT INTO districts VALUES ('643', 'Buôn Ma Thuột', 'Thành phố', '66');
INSERT INTO districts VALUES ('644', 'Thị Xã Buôn Hồ', 'Thị xã', '66');
INSERT INTO districts VALUES ('645', 'Ea H leo', 'Huyện', '66');
INSERT INTO districts VALUES ('646', 'Ea Súp', 'Huyện', '66');
INSERT INTO districts VALUES ('647', 'Buôn Đôn', 'Huyện', '66');
INSERT INTO districts VALUES ('648', 'Cư M gar', 'Huyện', '66');
INSERT INTO districts VALUES ('649', 'Krông Búk', 'Huyện', '66');
INSERT INTO districts VALUES ('650', 'Krông Năng', 'Huyện', '66');
INSERT INTO districts VALUES ('651', 'Ea Kar', 'Huyện', '66');
INSERT INTO districts VALUES ('652', 'M Đrắk', 'Huyện', '66');
INSERT INTO districts VALUES ('653', 'Krông Bông', 'Huyện', '66');
INSERT INTO districts VALUES ('654', 'Krông Pắc', 'Huyện', '66');
INSERT INTO districts VALUES ('655', 'Krông A Na', 'Huyện', '66');
INSERT INTO districts VALUES ('656', 'Lắk', 'Huyện', '66');
INSERT INTO districts VALUES ('657', 'Cư Kuin', 'Huyện', '66');
INSERT INTO districts VALUES ('660', 'Thị xã Gia Nghĩa', 'Thị xã', '67');
INSERT INTO districts VALUES ('661', 'Đăk Glong', 'Huyện', '67');
INSERT INTO districts VALUES ('662', 'Cư Jút', 'Huyện', '67');
INSERT INTO districts VALUES ('663', 'Đắk Mil', 'Huyện', '67');
INSERT INTO districts VALUES ('664', 'Krông Nô', 'Huyện', '67');
INSERT INTO districts VALUES ('665', 'Đắk Song', 'Huyện', '67');
INSERT INTO districts VALUES ('666', 'Đắk R Lấp', 'Huyện', '67');
INSERT INTO districts VALUES ('667', 'Tuy Đức', 'Huyện', '67');
INSERT INTO districts VALUES ('672', 'Đà Lạt', 'Thành phố', '68');
INSERT INTO districts VALUES ('673', 'Bảo Lộc', 'Thành phố', '68');
INSERT INTO districts VALUES ('674', 'Đam Rông', 'Huyện', '68');
INSERT INTO districts VALUES ('675', 'Lạc Dương', 'Huyện', '68');
INSERT INTO districts VALUES ('676', 'Lâm Hà', 'Huyện', '68');
INSERT INTO districts VALUES ('677', 'Đơn Dương', 'Huyện', '68');
INSERT INTO districts VALUES ('678', 'Đức Trọng', 'Huyện', '68');
INSERT INTO districts VALUES ('679', 'Di Linh', 'Huyện', '68');
INSERT INTO districts VALUES ('680', 'Bảo Lâm', 'Huyện', '68');
INSERT INTO districts VALUES ('681', 'Đạ Huoai', 'Huyện', '68');
INSERT INTO districts VALUES ('682', 'Đạ Tẻh', 'Huyện', '68');
INSERT INTO districts VALUES ('683', 'Cát Tiên', 'Huyện', '68');
INSERT INTO districts VALUES ('688', 'Thị xã Phước Long', 'Thị xã', '70');
INSERT INTO districts VALUES ('689', 'Thị xã Đồng Xoài', 'Thị xã', '70');
INSERT INTO districts VALUES ('690', 'Thị xã Bình Long', 'Thị xã', '70');
INSERT INTO districts VALUES ('691', 'Bù Gia Mập', 'Huyện', '70');
INSERT INTO districts VALUES ('692', 'Lộc Ninh', 'Huyện', '70');
INSERT INTO districts VALUES ('693', 'Bù Đốp', 'Huyện', '70');
INSERT INTO districts VALUES ('694', 'Hớn Quản', 'Huyện', '70');
INSERT INTO districts VALUES ('695', 'Đồng Phú', 'Huyện', '70');
INSERT INTO districts VALUES ('696', 'Bù Đăng', 'Huyện', '70');
INSERT INTO districts VALUES ('697', 'Chơn Thành', 'Huyện', '70');
INSERT INTO districts VALUES ('698', 'Phú Riềng', 'Huyện', '70');
INSERT INTO districts VALUES ('703', 'Tây Ninh', 'Thành phố', '72');
INSERT INTO districts VALUES ('705', 'Tân Biên', 'Huyện', '72');
INSERT INTO districts VALUES ('706', 'Tân Châu', 'Huyện', '72');
INSERT INTO districts VALUES ('707', 'Dương Minh Châu', 'Huyện', '72');
INSERT INTO districts VALUES ('708', 'Châu Thành', 'Huyện', '72');
INSERT INTO districts VALUES ('709', 'Hòa Thành', 'Huyện', '72');
INSERT INTO districts VALUES ('710', 'Gò Dầu', 'Huyện', '72');
INSERT INTO districts VALUES ('711', 'Bến Cầu', 'Huyện', '72');
INSERT INTO districts VALUES ('712', 'Trảng Bàng', 'Huyện', '72');
INSERT INTO districts VALUES ('718', 'Thủ Dầu Một', 'Thành phố', '74');
INSERT INTO districts VALUES ('719', 'Bàu Bàng', 'Huyện', '74');
INSERT INTO districts VALUES ('720', 'Dầu Tiếng', 'Huyện', '74');
INSERT INTO districts VALUES ('721', 'Thị xã Bến Cát', 'Thị xã', '74');
INSERT INTO districts VALUES ('722', 'Phú Giáo', 'Huyện', '74');
INSERT INTO districts VALUES ('723', 'Thị xã Tân Uyên', 'Thị xã', '74');
INSERT INTO districts VALUES ('724', 'Thị xã Dĩ An', 'Thị xã', '74');
INSERT INTO districts VALUES ('725', 'Thị xã Thuận An', 'Thị xã', '74');
INSERT INTO districts VALUES ('726', 'Bắc Tân Uyên', 'Huyện', '74');
INSERT INTO districts VALUES ('731', 'Biên Hòa', 'Thành phố', '75');
INSERT INTO districts VALUES ('732', 'Thị xã Long Khánh', 'Thị xã', '75');
INSERT INTO districts VALUES ('734', 'Tân Phú', 'Huyện', '75');
INSERT INTO districts VALUES ('735', 'Vĩnh Cửu', 'Huyện', '75');
INSERT INTO districts VALUES ('736', 'Định Quán', 'Huyện', '75');
INSERT INTO districts VALUES ('737', 'Trảng Bom', 'Huyện', '75');
INSERT INTO districts VALUES ('738', 'Thống Nhất', 'Huyện', '75');
INSERT INTO districts VALUES ('739', 'Cẩm Mỹ', 'Huyện', '75');
INSERT INTO districts VALUES ('740', 'Long Thành', 'Huyện', '75');
INSERT INTO districts VALUES ('741', 'Xuân Lộc', 'Huyện', '75');
INSERT INTO districts VALUES ('742', 'Nhơn Trạch', 'Huyện', '75');
INSERT INTO districts VALUES ('747', 'Vũng Tàu', 'Thành phố', '77');
INSERT INTO districts VALUES ('748', 'Bà Rịa', 'Thành phố', '77');
INSERT INTO districts VALUES ('750', 'Châu Đức', 'Huyện', '77');
INSERT INTO districts VALUES ('751', 'Xuyên Mộc', 'Huyện', '77');
INSERT INTO districts VALUES ('752', 'Long Điền', 'Huyện', '77');
INSERT INTO districts VALUES ('753', 'Đất Đỏ', 'Huyện', '77');
INSERT INTO districts VALUES ('754', 'Tân Thành', 'Huyện', '77');
INSERT INTO districts VALUES ('755', 'Côn Đảo', 'Huyện', '77');
INSERT INTO districts VALUES ('760', '1', 'Quận', '79');
INSERT INTO districts VALUES ('761', '12', 'Quận', '79');
INSERT INTO districts VALUES ('762', 'Thủ Đức', 'Quận', '79');
INSERT INTO districts VALUES ('763', '9', 'Quận', '79');
INSERT INTO districts VALUES ('764', 'Gò Vấp', 'Quận', '79');
INSERT INTO districts VALUES ('765', 'Bình Thạnh', 'Quận', '79');
INSERT INTO districts VALUES ('766', 'Tân Bình', 'Quận', '79');
INSERT INTO districts VALUES ('767', 'Tân Phú', 'Quận', '79');
INSERT INTO districts VALUES ('768', 'Phú Nhuận', 'Quận', '79');
INSERT INTO districts VALUES ('769', '2', 'Quận', '79');
INSERT INTO districts VALUES ('770', '3', 'Quận', '79');
INSERT INTO districts VALUES ('771', '10', 'Quận', '79');
INSERT INTO districts VALUES ('772', '11', 'Quận', '79');
INSERT INTO districts VALUES ('773', '4', 'Quận', '79');
INSERT INTO districts VALUES ('774', '5', 'Quận', '79');
INSERT INTO districts VALUES ('775', '6', 'Quận', '79');
INSERT INTO districts VALUES ('776', '8', 'Quận', '79');
INSERT INTO districts VALUES ('777', 'Bình Tân', 'Quận', '79');
INSERT INTO districts VALUES ('778', '7', 'Quận', '79');
INSERT INTO districts VALUES ('783', 'Củ Chi', 'Huyện', '79');
INSERT INTO districts VALUES ('784', 'Hóc Môn', 'Huyện', '79');
INSERT INTO districts VALUES ('785', 'Bình Chánh', 'Huyện', '79');
INSERT INTO districts VALUES ('786', 'Nhà Bè', 'Huyện', '79');
INSERT INTO districts VALUES ('787', 'Cần Giờ', 'Huyện', '79');
INSERT INTO districts VALUES ('794', 'Tân An', 'Thành phố', '80');
INSERT INTO districts VALUES ('795', 'Thị xã Kiến Tường', 'Thị xã', '80');
INSERT INTO districts VALUES ('796', 'Tân Hưng', 'Huyện', '80');
INSERT INTO districts VALUES ('797', 'Vĩnh Hưng', 'Huyện', '80');
INSERT INTO districts VALUES ('798', 'Mộc Hóa', 'Huyện', '80');
INSERT INTO districts VALUES ('799', 'Tân Thạnh', 'Huyện', '80');
INSERT INTO districts VALUES ('800', 'Thạnh Hóa', 'Huyện', '80');
INSERT INTO districts VALUES ('801', 'Đức Huệ', 'Huyện', '80');
INSERT INTO districts VALUES ('802', 'Đức Hòa', 'Huyện', '80');
INSERT INTO districts VALUES ('803', 'Bến Lức', 'Huyện', '80');
INSERT INTO districts VALUES ('804', 'Thủ Thừa', 'Huyện', '80');
INSERT INTO districts VALUES ('805', 'Tân Trụ', 'Huyện', '80');
INSERT INTO districts VALUES ('806', 'Cần Đước', 'Huyện', '80');
INSERT INTO districts VALUES ('807', 'Cần Giuộc', 'Huyện', '80');
INSERT INTO districts VALUES ('808', 'Châu Thành', 'Huyện', '80');
INSERT INTO districts VALUES ('815', 'Mỹ Tho', 'Thành phố', '82');
INSERT INTO districts VALUES ('816', 'Thị xã Gò Công', 'Thị xã', '82');
INSERT INTO districts VALUES ('817', 'Thị xã Cai Lậy', 'Huyện', '82');
INSERT INTO districts VALUES ('818', 'Tân Phước', 'Huyện', '82');
INSERT INTO districts VALUES ('819', 'Cái Bè', 'Huyện', '82');
INSERT INTO districts VALUES ('820', 'Cai Lậy', 'Thị xã', '82');
INSERT INTO districts VALUES ('821', 'Châu Thành', 'Huyện', '82');
INSERT INTO districts VALUES ('822', 'Chợ Gạo', 'Huyện', '82');
INSERT INTO districts VALUES ('823', 'Gò Công Tây', 'Huyện', '82');
INSERT INTO districts VALUES ('824', 'Gò Công Đông', 'Huyện', '82');
INSERT INTO districts VALUES ('825', 'Tân Phú Đông', 'Huyện', '82');
INSERT INTO districts VALUES ('829', 'Bến Tre', 'Thành phố', '83');
INSERT INTO districts VALUES ('831', 'Châu Thành', 'Huyện', '83');
INSERT INTO districts VALUES ('832', 'Chợ Lách', 'Huyện', '83');
INSERT INTO districts VALUES ('833', 'Mỏ Cày Nam', 'Huyện', '83');
INSERT INTO districts VALUES ('834', 'Giồng Trôm', 'Huyện', '83');
INSERT INTO districts VALUES ('835', 'Bình Đại', 'Huyện', '83');
INSERT INTO districts VALUES ('836', 'Ba Tri', 'Huyện', '83');
INSERT INTO districts VALUES ('837', 'Thạnh Phú', 'Huyện', '83');
INSERT INTO districts VALUES ('838', 'Mỏ Cày Bắc', 'Huyện', '83');
INSERT INTO districts VALUES ('842', 'Trà Vinh', 'Thành phố', '84');
INSERT INTO districts VALUES ('844', 'Càng Long', 'Huyện', '84');
INSERT INTO districts VALUES ('845', 'Cầu Kè', 'Huyện', '84');
INSERT INTO districts VALUES ('846', 'Tiểu Cần', 'Huyện', '84');
INSERT INTO districts VALUES ('847', 'Châu Thành', 'Huyện', '84');
INSERT INTO districts VALUES ('848', 'Cầu Ngang', 'Huyện', '84');
INSERT INTO districts VALUES ('849', 'Trà Cú', 'Huyện', '84');
INSERT INTO districts VALUES ('850', 'Duyên Hải', 'Huyện', '84');
INSERT INTO districts VALUES ('851', 'Thị xã Duyên Hải', 'Thị xã', '84');
INSERT INTO districts VALUES ('855', 'Vĩnh Long', 'Thành phố', '86');
INSERT INTO districts VALUES ('857', 'Long Hồ', 'Huyện', '86');
INSERT INTO districts VALUES ('858', 'Mang Thít', 'Huyện', '86');
INSERT INTO districts VALUES ('859', ' Vũng Liêm', 'Huyện', '86');
INSERT INTO districts VALUES ('860', 'Tam Bình', 'Huyện', '86');
INSERT INTO districts VALUES ('861', 'Thị xã Bình Minh', 'Thị xã', '86');
INSERT INTO districts VALUES ('862', 'Trà Ôn', 'Huyện', '86');
INSERT INTO districts VALUES ('863', 'Bình Tân', 'Huyện', '86');
INSERT INTO districts VALUES ('866', 'Cao Lãnh', 'Thành phố', '87');
INSERT INTO districts VALUES ('867', 'Sa Đéc', 'Thành phố', '87');
INSERT INTO districts VALUES ('868', 'Thị xã Hồng Ngự', 'Thị xã', '87');
INSERT INTO districts VALUES ('869', 'Tân Hồng', 'Huyện', '87');
INSERT INTO districts VALUES ('870', 'Hồng Ngự', 'Huyện', '87');
INSERT INTO districts VALUES ('871', 'Tam Nông', 'Huyện', '87');
INSERT INTO districts VALUES ('872', 'Tháp Mười', 'Huyện', '87');
INSERT INTO districts VALUES ('873', 'Cao Lãnh', 'Huyện', '87');
INSERT INTO districts VALUES ('874', 'Thanh Bình', 'Huyện', '87');
INSERT INTO districts VALUES ('875', 'Lấp Vò', 'Huyện', '87');
INSERT INTO districts VALUES ('876', 'Lai Vung', 'Huyện', '87');
INSERT INTO districts VALUES ('877', 'Châu Thành', 'Huyện', '87');
INSERT INTO districts VALUES ('883', 'Long Xuyên', 'Thành phố', '89');
INSERT INTO districts VALUES ('884', 'Châu Đốc', 'Thành phố', '89');
INSERT INTO districts VALUES ('886', 'An Phú', 'Huyện', '89');
INSERT INTO districts VALUES ('887', 'Thị xã Tân Châu', 'Thị xã', '89');
INSERT INTO districts VALUES ('888', 'Phú Tân', 'Huyện', '89');
INSERT INTO districts VALUES ('889', 'Châu Phú', 'Huyện', '89');
INSERT INTO districts VALUES ('890', 'Tịnh Biên', 'Huyện', '89');
INSERT INTO districts VALUES ('891', 'Tri Tôn', 'Huyện', '89');
INSERT INTO districts VALUES ('892', 'Châu Thành', 'Huyện', '89');
INSERT INTO districts VALUES ('893', 'Chợ Mới', 'Huyện', '89');
INSERT INTO districts VALUES ('894', 'Thoại Sơn', 'Huyện', '89');
INSERT INTO districts VALUES ('899', 'Rạch Giá', 'Thành phố', '91');
INSERT INTO districts VALUES ('900', 'Thị xã Hà Tiên', 'Thị xã', '91');
INSERT INTO districts VALUES ('902', 'Kiên Lương', 'Huyện', '91');
INSERT INTO districts VALUES ('903', 'Hòn Đất', 'Huyện', '91');
INSERT INTO districts VALUES ('904', 'Tân Hiệp', 'Huyện', '91');
INSERT INTO districts VALUES ('905', 'Châu Thành', 'Huyện', '91');
INSERT INTO districts VALUES ('906', 'Giồng Riềng', 'Huyện', '91');
INSERT INTO districts VALUES ('907', 'Gò Quao', 'Huyện', '91');
INSERT INTO districts VALUES ('908', 'An Biên', 'Huyện', '91');
INSERT INTO districts VALUES ('909', 'An Minh', 'Huyện', '91');
INSERT INTO districts VALUES ('910', 'Vĩnh Thuận', 'Huyện', '91');
INSERT INTO districts VALUES ('911', 'Phú Quốc', 'Huyện', '91');
INSERT INTO districts VALUES ('912', 'Kiên Hải', 'Huyện', '91');
INSERT INTO districts VALUES ('913', 'U Minh Thượng', 'Huyện', '91');
INSERT INTO districts VALUES ('914', 'Giang Thành', 'Huyện', '91');
INSERT INTO districts VALUES ('916', 'Ninh Kiều', 'Quận', '92');
INSERT INTO districts VALUES ('917', 'Ô Môn', 'Quận', '92');
INSERT INTO districts VALUES ('918', 'Bình Thuỷ', 'Quận', '92');
INSERT INTO districts VALUES ('919', 'Cái Răng', 'Quận', '92');
INSERT INTO districts VALUES ('923', 'Thốt Nốt', 'Quận', '92');
INSERT INTO districts VALUES ('924', 'Vĩnh Thạnh', 'Huyện', '92');
INSERT INTO districts VALUES ('925', 'Cờ Đỏ', 'Huyện', '92');
INSERT INTO districts VALUES ('926', 'Phong Điền', 'Huyện', '92');
INSERT INTO districts VALUES ('927', 'Thới Lai', 'Huyện', '92');
INSERT INTO districts VALUES ('930', 'Vị Thanh', 'Thành phố', '93');
INSERT INTO districts VALUES ('931', 'Thị xã Ngã Bảy', 'Thị xã', '93');
INSERT INTO districts VALUES ('932', 'Châu Thành A', 'Huyện', '93');
INSERT INTO districts VALUES ('933', 'Châu Thành', 'Huyện', '93');
INSERT INTO districts VALUES ('934', 'Phụng Hiệp', 'Huyện', '93');
INSERT INTO districts VALUES ('935', 'Vị Thuỷ', 'Huyện', '93');
INSERT INTO districts VALUES ('936', 'Long Mỹ', 'Huyện', '93');
INSERT INTO districts VALUES ('937', 'Thị xã Long Mỹ', 'Thị xã', '93');
INSERT INTO districts VALUES ('941', 'Sóc Trăng', 'Thành phố', '94');
INSERT INTO districts VALUES ('942', 'Châu Thành', 'Huyện', '94');
INSERT INTO districts VALUES ('943', 'Kế Sách', 'Huyện', '94');
INSERT INTO districts VALUES ('944', 'Mỹ Tú', 'Huyện', '94');
INSERT INTO districts VALUES ('945', 'Cù Lao Dung', 'Huyện', '94');
INSERT INTO districts VALUES ('946', 'Long Phú', 'Huyện', '94');
INSERT INTO districts VALUES ('947', 'Mỹ Xuyên', 'Huyện', '94');
INSERT INTO districts VALUES ('948', 'Thị xã Ngã Năm', 'Thị xã', '94');
INSERT INTO districts VALUES ('949', 'Thạnh Trị', 'Huyện', '94');
INSERT INTO districts VALUES ('950', 'Thị xã Vĩnh Châu', 'Thị xã', '94');
INSERT INTO districts VALUES ('951', 'Trần Đề', 'Huyện', '94');
INSERT INTO districts VALUES ('954', 'Bạc Liêu', 'Thành phố', '95');
INSERT INTO districts VALUES ('956', 'Hồng Dân', 'Huyện', '95');
INSERT INTO districts VALUES ('957', 'Phước Long', 'Huyện', '95');
INSERT INTO districts VALUES ('958', 'Vĩnh Lợi', 'Huyện', '95');
INSERT INTO districts VALUES ('959', 'Thị xã Giá Rai', 'Thị xã', '95');
INSERT INTO districts VALUES ('960', 'Đông Hải', 'Huyện', '95');
INSERT INTO districts VALUES ('961', 'Hoà Bình', 'Huyện', '95');
INSERT INTO districts VALUES ('964', 'Cà Mau', 'Thành phố', '96');
INSERT INTO districts VALUES ('966', 'U Minh', 'Huyện', '96');
INSERT INTO districts VALUES ('967', 'Thới Bình', 'Huyện', '96');
INSERT INTO districts VALUES ('968', 'Trần Văn Thời', 'Huyện', '96');
INSERT INTO districts VALUES ('969', 'Cái Nước', 'Huyện', '96');
INSERT INTO districts VALUES ('970', 'Đầm Dơi', 'Huyện', '96');
INSERT INTO districts VALUES ('971', 'Năm Căn', 'Huyện', '96');
INSERT INTO districts VALUES ('972', 'Phú Tân', 'Huyện', '96');
INSERT INTO districts VALUES ('973', 'Ngọc Hiển', 'Huyện', '96');
